export const Genre_const = [
  "action",
  "adventure",
  "cars",
  "comedy",
  "dementia",
  "demons",
  "drama",
  "ecchi",
  "fantasy",
  "game",
  "harem",
  "historical",
  "horror",
  "josei",
  "kids",
  "magic",
  "martialarts",
  "mecha",
  "military",
  "music",
  "mystery",
  "police",
  "psychological",
  "romance",
  "samurai",
  "school",
  "sci-fi",
  "seinen",
  "shoujo",
  "shoujoai",
  "shounen",
  "shounenai",
  "sliceoflife",
  "space",
  "sports",
  "supernatural",
  "superpower",
  "thriller",
  "vampire",
];
export const Studio_const = [
  "A.C.G.T.",
  "AIC",
  "Asread",
  "Bee Train",
  "Bones",
  "Daume",
  "Digital Frontier",
  "Gainax",
  "Gallop",
  "Gonzo",
  "Group TAC",
  "Hal Film Maker",
  "Imagin",
  "J.C.Staff",
  "Kyoto Animation",
  "Madhouse",
  "Nakamura Production",
  "Nippon Animation",
  "Nomad",
  "OLM",
  "Production I.G",
  "Seven Arcs",
  "Shaft",
  "Studio Comet",
  "Studio Deen",
  "Studio Fantasia",
  "Studio Flag",
  "Studio Ghibli",
  "Studio Hibari",
  "Studio Live",
  "Studio Matrix",
  "Studio Pierrot",
  "Sunrise",
  "TMS Entertainment",
  "TNK",
  "Tatsunoko Production",
  "Telecom Animation Film",
  "Toei Animation",
  "Tokyo Movie Shinsha",
  "Trans Arts",
  "Xebec",
  "Zexcs",
  "feel.",
  "ufotable",
];
const tempYear = [];
for (let i = 1975; i < 2006; i++) {
  tempYear.push(i);
}
export const year_const = tempYear;
